title: MGA 312: An Introduction to Data Analytics for Accountants
description: MGA 312 Course Website
theme: just-the-docs

url: "https://vcastellani.github.io"
baseurl: "/MGA312"

footer_content: "Copyright Â© 2025 Vincent Castellani"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
